In [18]:
import numpy as np, pandas as pd
import scipy

user_movie_matrix = np.array(((1,5,0,5,4), (5,4,4,3,2), (0,4,0,0,5), (4,4,1,4,0), (0,4,3,5,0), (2,4,3,5,3)))

U, s, V = scipy.linalg.svd(user_movie_matrix) 

v2r = V[:2]
#print(v2r)

user2 = user_movie_matrix[1:2]
print(user2)

lowdim = user2.dot(np.transpose(v2r))
print(lowdim)

it = lowdim.dot(v2r)
print(it)


new_user = np.array((0, 0, 3, 4, 0))
v3r = V[:3]
lowdimnu = new_user.dot(np.transpose(v3r))
itnu = lowdimnu.dot(v3r)
print(itnu)

[[5 4 4 3 2]]
[[-7.58783957 -1.90605029]]
[[3.19719556 4.22057993 2.91894245 4.851947   1.05421441]]
[ 0.40015936  1.52990144  1.47154395  3.57090597 -1.13168846]
