In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.mixture import GaussianMixture

n_samples = 1500
dataset = datasets.make_blobs(n_samples=n_samples, centers=2, center_box=(-7.0, 7.5),
                              cluster_std=[1.4, 1.7],
                              random_state=42)
X_2, _ = datasets.make_blobs(n_samples=n_samples, random_state=170, centers=[[-4, -3]], cluster_std=[1.9])
transformation = [[1.2, -0.8], [-0.4, 1.7]]
X_2 = np.dot(X_2, transformation)
X, y = np.concatenate((dataset[0], X_2)), np.concatenate((dataset[1], np.array([2] * len(X_2))))

#plt.rcParams['figure.figsize'] = 10, 10
#plt.scatter(X[:, 0], X[:, 1], c=y, alpha=0.5)
#plt.show()

unique, counts = np.unique(y, return_counts=True)
print(dict(zip(unique, counts)))

gm = GaussianMixture(n_components=3, random_state=42)
y_pred = gm.fit_predict(X)
means = gm.means_
print(np.round(means).astype(int))

_, counts = np.unique(y_pred, return_counts=True)
print(_)
print(counts)


{0: 750, 1: 750, 2: 1500}
[[-2  7]
 [-4 -2]
 [ 4  2]]
[0 1 2]
[ 763 1493  744]
